apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oauth-app-cred
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  client_id: '<base64-encoded OAuth app clientID>'
  client_secret: '<base64-encoded OAuth app clientSecret>'

#stringData:
  #client_id: '<OAuth app clientID(directly)>'
  #client_secret: '<OAuth app clientSecret(directly)>'
